### ISSUE TITLE
Feature request: Parallelisation for Windows

### ISSUE THREAD

**Issue by KathaSchmack** [gloewing/photometry_FLMM#1]
It seems that "fui" cannot be run with parallel = TRUE on Windows. It produces the following error:
Error in mclapply(argvals, unimm, mc.cores = num_cores) : 
  'mc.cores' > 1 is not supported on Windows

**Comment by gloewing** [comment]
Did you first install the new fastFMM version? That error makes sense for
the old fui() version but on the new one, Windows should use a different
parallelization function.

**Comment by KathaSchmack** [comment]
Thank you! This happens with the fastFMM version 0.2.0 which got installed when I ran install.packages("fastFMM", dependencies = TRUE).

**Comment by gloewing** [comment]
That makes sense: I don't think the new *fastFMM* version (with PC
parallelization capability) has been added to CRAN yet (hopefully it will
be in 1-2 weeks). But you can still download the new *fastFMM *version
(with PC parallelization capability) with the following code:

install.packages('devtools') # not necessary if you already have devtools
installed
devtools::install_github('gloewing/fastFMM')

Let me know if parallelization works after you install the new version.

**Comment by KathaSchmack** [comment]
Fantastic, that worked, thank you!
