### ISSUE TITLE
Error for function 'as.matrix': element (1, 1) is zero, so the inverse cannot be computed

### ISSUE THREAD

**Issue by KathaSchmack** [gloewing/photometry_FLMM#2]
I have been playing around with the toolbox, which is very easy to use and looks very powerful! Sometimes I get this error: 

mod1 = fui(photometry ~ outcome + (1 | sessionId), data = data, parallel = TRUE) 
[1] "Step 1: Fit Massively Univariate Mixed Models"
[1] "Finished fitting univariate models."
[1] "Step 2: Smoothing"
[1] "Step 3: Inference (Analytic)"
[1] "Step 3.1: Preparation"
[1] "Step 3.1.1: Method of Moments Covariance Estimator Random Intercept"
[1] "Step 3.1.2: Smooth G"
[1] "Step 3.2: First step"
Error in value[[3L]](cond) : 
  Error when parallelizing variance calculations:
Error in checkForRemoteErrors(val): one node produced an error: error in evaluating the argument 'x' in selecting a method for function 'as.matrix': element (1, 1) is zero, so the inverse cannot be computed

The data does not contain any nans, and the model runs fine for a similar analysis on photometry data recorded at the same time in a parallel channel.

**Comment by gloewing** [comment]
Does the same error occur if parallel=FALSE?

**Comment by KathaSchmack** [comment]
Yes, same error I am afraid:

`Error in h(simpleError(msg, call)) :    error in evaluating the argument 'x' in selecting a method for function 'as.matrix': element (1, 1) is zero, so the inverse cannot be computed
`

**Comment by gloewing** [comment]
Hmmm, that’s funny. If you send me a dataset that can reproduce the error I
can try to troubleshoot it.

**Comment by gloewing** [comment]
As we discussed via email, this issue came from a non invertible matrix for one point on the functional domain (a trial timepoint at the very end of the trial). Removing this trial timepoint from the analysis resolved this issue.
