### ISSUE TITLE
Feature request: models without random effects

### ISSUE THREAD

**Issue by oguienko** [gloewing/photometry_FLMM#4]
Hi! 
As far as I understand, there are no models without random effects implemented in the software yet. Is it possible/legitimate to add them?

I do experiments where it is only possible to get one measurement from one mouse, and I need to compare control and treatment groups. The experiment involves abusive substance injection with a long-term effect (several hours), so it's not possible to do multiple trials per session, and we think that the sensitivity to the drug changes over time. Thus, one measurement per mouse. I get an error when trying to add mouse ID as a random effect since the number of observations equals the number of a grouping factor.

Any help/advice would be greatly appreciated!

**Comment by gloewing** [comment]
Hey I just responded to your other message and I think my response to it
should cover this question, but let me know if you have any other questions.

Best,
Gabe
